---
title: "678 Midterm"
author: "Kaiyu Yan"
date: "November 24, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
```

```{r}
#Import orginal datasets
Player_stats <- read_xlsx("Player Rushing.xlsx")
PowerIndex <- read_xlsx("Power Index.xlsx")
Team_Efficience <- read_xlsx("Team Efficience.xlsx")
Team_R_Defense <- read_xlsx("Team Rushing Defense Stats.xlsx")
Team_R_Offense <- read_xlsx("Team Rushing Offense Stats.xlsx")
BTN_Rushing <- read_excel("BTN Rushing.xlsx")
BTN_Schedule <- read_xlsx("Schedule.xlsx")
```

```{r}
BTN_School_Abb <- c("MSU","MICH","PUR","MD","OSU","NEB","RUTG","PSU","NW","IND","WIS","MINN","ILL","IOWA")
BTN_School_Full <- c("Minnesota","Northwestern","Purdue","Michigan State","Wisconsin","Maryland","Ohio State","Rutgers","Illinois","Penn State","Iowa","Indiana","Michigan","Nebraska","Mich. St")
Non_BTN <- c("Central Michigan","Eastern Michigan","Northern Illinois","Western Michigan","Iowa State","Cent Michigan","E Michigan","N Illinois","W Michigan")
BTN_Player <- filter(Player_stats,str_detect(Player_stats$TEAM,paste(BTN_School_Abb, collapse = '|'))) 
BTN_Player <- filter(BTN_Player,!str_detect(BTN_Player$TEAM,"NMSU")) 
Data<- data.frame(do.call('rbind', strsplit(as.character(BTN_Player$PLAYER),',',fixed=TRUE)))
BTN_Player <- merge(BTN_Player,Data,by = 0) 
BTN_Player <- select(BTN_Player,4:11)
names(BTN_Player)[7] <- paste("Fullname")
names(BTN_Player)[8] <- paste("Position")
names(BTN_Player)[2] <- paste("Total.ATT")
names(BTN_Player)[3] <- paste("Total.YDS")
names(BTN_Player)[4] <- paste("Total.YDS.Attempt")
names(BTN_Player)[6] <- paste("Total.TD")
BTN_Player<- filter(BTN_Player,str_detect(BTN_Player$Position,"RB"))
BTN_Player$Total.ATT <- as.numeric(BTN_Player$Total.ATT)
BTN_Player$`Total.YDS.Attempt` <- as.numeric(BTN_Player$`Total.YDS.Attempt`)

BTN_Rushing<-unite(BTN_Rushing,Fullname,1,2,sep = " ",remove = TRUE)
BTN_Rushing<-BTN_Rushing[complete.cases(BTN_Rushing),]

BTN_R_Defense <- filter(Team_R_Defense,str_detect(Team_R_Defense$TEAM,paste(BTN_School_Full, collapse = '|'))) 
BTN_R_Defense <- filter(BTN_R_Defense,!str_detect(BTN_R_Defense$TEAM,paste(Non_BTN,collapse = '|'))) 
names(BTN_R_Defense)[3] <- paste("ATT.Allowed")
names(BTN_R_Defense)[4] <- paste("Total.YDS.Allowed")
names(BTN_R_Defense)[5] <- paste("YDS/Attempt.Allowed")
names(BTN_R_Defense)[8] <- paste("YDS/Game.Allowed")

BTN_R_Offense  <- filter(Team_R_Offense,str_detect(Team_R_Offense$TEAM,paste(BTN_School_Full, collapse = '|'))) 
BTN_R_Offense  <- filter(BTN_R_Defense,!str_detect(BTN_R_Defense$TEAM,paste(Non_BTN,collapse = '|'))) 


BTN_Efficience <- filter(Team_Efficience,str_detect(Team_Efficience$TEAM,paste(BTN_School_Full, collapse = '|'))) 
BTN_Efficience <- filter(BTN_Efficience,!str_detect(BTN_Efficience$TEAM,paste(Non_BTN,collapse = '|')))
Data1<- data.frame(do.call('rbind', strsplit(as.character(BTN_Efficience$TEAM),',',fixed=TRUE)))
BTN_Efficience <- merge(BTN_Efficience,Data1,by = 0) 
BTN_Efficience <- select(BTN_Efficience,4:8)
names(BTN_Efficience)[5] <- paste("School")


BTN_PI <- filter(PowerIndex,str_detect(PowerIndex$TEAM,paste(BTN_School_Full, collapse = '|'))) 
BTN_PI <- filter(BTN_PI,!str_detect(BTN_PI$TEAM,paste(Non_BTN,collapse = '|'))) 
Data2<- data.frame(do.call('rbind', strsplit(as.character(BTN_PI$TEAM),',',fixed=TRUE)))
BTN_PI <- merge(BTN_PI,Data2,by = 0) 
BTN_PI <- select(BTN_PI,9:10)
names(BTN_PI)[2] <- paste("School")

School_Code <- inner_join(BTN_PI,BTN_Efficience,by="School")
School_Code$School <- as.character(School_Code$School)


Player <- inner_join(BTN_Player,BTN_Rushing,by="Fullname")
Final <- inner_join(Player,School_Code,by = "School") %>% 
  select(2:4,7:13,17:20,22)

Data3<- data.frame(do.call('rbind', strsplit(as.character(PowerIndex$TEAM),',',fixed=TRUE)))
PowerIndex <- merge(PowerIndex,Data3,by = 0) 
PowerIndex <- select(PowerIndex,9:10)
names(PowerIndex)[2] <- paste("Opponent")

BTN_Schedule <- inner_join(PowerIndex,BTN_Schedule,by="Opponent")

Data4<- data.frame(do.call('rbind', strsplit(as.character(Team_Efficience$TEAM),',',fixed=TRUE)))
Team_Efficience <- merge(Team_Efficience,Data4,by = 0)
Team_Efficience <- select(Team_Efficience,4:8)
names(Team_Efficience)[5] <- paste("Opponent")
BTN_Schedule <- inner_join(Team_Efficience,BTN_Schedule,by="Opponent")


```

```{r}
WIS <- filter(Player,str_detect(Player$TEAM,"WIS"))
wis_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Wisconsin"))
wis_schedule <- inner_join(wis_schedule,School_Code,by="School")
WIS <- inner_join(WIS,wis_schedule,by="Week")

OSU <- filter(Player,str_detect(Player$TEAM,"OSU"))
osu_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Ohio State"))
osu_schedule <- inner_join(osu_schedule,School_Code,by="School")
OSU <- inner_join(OSU,osu_schedule,by="Week")

MSU<- filter(Player,str_detect(Player$TEAM,"MSU"))
msu_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Mich. St."))
msu_schedule <- inner_join(msu_schedule,School_Code,by="School")
MSU <- inner_join(MSU,msu_schedule,by="Week")

MICH<- filter(Player,str_detect(Player$TEAM,"MICH"))
mich_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Michigan"))
mich_schedule <- inner_join(mich_schedule,School_Code,by="School")
MICH <- inner_join(MICH,mich_schedule,by="Week")

NE<- filter(Player,str_detect(Player$TEAM,"NEB"))
neb_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Nebraska"))
neb_schedule <- inner_join(neb_schedule,School_Code,by="School")
NE <- inner_join(NE,neb_schedule,by="Week")

IOWA<- filter(Player,str_detect(Player$TEAM,"IOWA"))
iowa_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Iowa"))
iowa_schedule <- inner_join(iowa_schedule,School_Code,by="School")
IOWA <- inner_join(IOWA,iowa_schedule,by="Week")

IND<- filter(Player,str_detect(Player$TEAM,"IND"))
ind_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Indiana"))
ind_schedule <- inner_join(ind_schedule,School_Code,by="School")
IND <- inner_join(IND,ind_schedule,by="Week")

ILL<- filter(Player,str_detect(Player$TEAM,"ILL"))
ill_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Illinois"))
ill_schedule <- inner_join(ill_schedule,School_Code,by="School")
ILL <- inner_join(ILL,ill_schedule,by="Week")

MD<- filter(Player,str_detect(Player$TEAM,"MD"))
md_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Maryland"))
md_schedule <- inner_join(md_schedule,School_Code,by="School")
MD <- inner_join(MD,md_schedule,by="Week")

PSU<- filter(Player,str_detect(Player$TEAM,"PSU"))
psu_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Penn State"))
psu_schedule <- inner_join(psu_schedule,School_Code,by="School")
PSU <- inner_join(PSU,psu_schedule,by="Week")

NW<- filter(Player,str_detect(Player$TEAM,"NW"))
nw_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Northwestern"))
nw_schedule <- inner_join(nw_schedule,School_Code,by="School")
NW <- inner_join(NW,nw_schedule,by="Week")

PUR <- filter(Player,str_detect(Player$TEAM,"PUR"))
pur_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Purdue"))
pur_schedule <- inner_join(pur_schedule,School_Code,by="School")
PUR <- inner_join(PUR,pur_schedule,by="Week")

MINN<- filter(Player,str_detect(Player$TEAM,"MINN"))
minn_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Minnesota"))
minn_schedule <- inner_join(minn_schedule,School_Code,by="School")
MINN <- inner_join(MINN,minn_schedule,by="Week")

RUT <- filter(Player,str_detect(Player$TEAM,"RUTG"))
rut_schedule <- filter(BTN_Schedule,str_detect(BTN_Schedule$School,"Purdue"))
rut_schedule <- inner_join(rut_schedule,School_Code,by="School")
RUT <- inner_join(RUT,rut_schedule,by="Week")


Final_Data <- rbind(WIS,RUT,MINN,PUR,NW,PSU,OSU,NE,MSU,MICH,MD,ILL,IND,IOWA) 
Final_Data <- select(Final_Data,1:4,7,10:12,17:19,22,23,25:27)

```

```{r}
names(Final_Data)[2] <- paste("Player.Total.ATT")
names(Final_Data)[3] <- paste("Player.Total.YDS")
names(Final_Data)[4] <- paste("Player.Total.YDS.Per.ATT")
names(Final_Data)[5] <- paste("Player.Name")
names(Final_Data)[6] <- paste("Weekly.ATT")
names(Final_Data)[7] <- paste("Weekly.YDS")
names(Final_Data)[8] <- paste("Weekly.YDS.Per.ATT")
names(Final_Data)[10] <- paste("Opponent.Offense.Index")
names(Final_Data)[11] <- paste("Opponent.Defense.Index")
names(Final_Data)[13] <- paste("Opponent.Power.Index")
names(Final_Data)[14] <- paste("Team.Power.Index")
names(Final_Data)[15] <- paste("Team.Offense.Inde")
names(Final_Data)[16] <- paste("Team.Defense.Inde")
Final_Data[,10]<- as.numeric(Final_Data[,10])
Final_Data[,11]<- as.numeric(Final_Data[,11])
Final_Data[,13]<- as.numeric(Final_Data[,13])
Final_Data[,14]<- as.numeric(Final_Data[,14])
Final_Data[,15]<- as.numeric(Final_Data[,15])
Final_Data[,16]<- as.numeric(Final_Data[,16])

```



